"""add voice_file_path

Revision ID: c3f60bccafcf
Revises: db3230f09688
Create Date: 2026-01-14 08:17:38.017234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f60bccafcf'
down_revision: Union[str, None] = 'db3230f09688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('voice_file_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'voice_file_path')
    # ### end Alembic commands ###
